apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    app.openshift.io/description: Executes logic to build, tag and push a container
      image using the intermediate sha tag to the image-url
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    description: Executes logic to build, tag and push a container image using the
      intermediate sha tag to the image-url
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"app.openshift.io/description":"Executes logic to build, tag and push a container image using the intermediate sha tag to the image-url","app.openshift.io/vcs-ref":"master","app.openshift.io/vcs-uri":"https://github.com/IBM/ibm-garage-tekton-tasks","description":"Executes logic to build, tag and push a container image using the intermediate sha tag to the image-url"},"labels":{"version":"2.5.0"},"name":"ibm-build-tag-push-v2-5-0","namespace":"tools"},"spec":{"params":[{"name":"git-url"},{"default":"master","name":"git-revision"},{"default":"/source","name":"source-dir"},{"default":"","name":"image-server"},{"default":"","name":"image-namespace"},{"default":"","name":"image-repository"},{"default":"","name":"image-tag"},{"default":"quay.io/buildah/stable:v1.15.0","name":"BUILDER_IMAGE"},{"default":"./Dockerfile","name":"DOCKERFILE"},{"default":".","name":"CONTEXT"},{"default":"false","name":"TLSVERIFY"},{"default":"docker","name":"FORMAT"},{"default":"overlay","description":"Set buildah storage driver","name":"STORAGE_DRIVER"}],"stepTemplate":{"volumeMounts":[{"mountPath":"$(params.source-dir)","name":"source"}]},"steps":[{"env":[{"name":"GIT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"git-credentials","optional":true}}},{"name":"GIT_USERNAME","valueFrom":{"secretKeyRef":{"key":"username","name":"git-credentials","optional":true}}}],"image":"quay.io/ibmgaragecloud/alpine-git","name":"git-clone","script":"set +x\nif [[ -n \"${GIT_USERNAME}\" ]] \u0026\u0026 [[ -n \"${GIT_PASSWORD}\" ]]; then\n    git clone \"$(echo $(params.git-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PASSWORD}@$(echo $(params.git-url) | awk -F '://' '{print $2}')\" $(params.source-dir)\nelse\n    set -x\n    git clone $(params.git-url) $(params.source-dir)\nfi\nset -x\ncd $(params.source-dir)\ngit checkout $(params.git-revision)\n"},{"env":[{"name":"REGISTRY_USER","valueFrom":{"secretKeyRef":{"key":"REGISTRY_USER","name":"registry-access","optional":true}}},{"name":"REGISTRY_PASSWORD","valueFrom":{"secretKeyRef":{"key":"REGISTRY_PASSWORD","name":"registry-access","optional":true}}}],"image":"$(params.BUILDER_IMAGE)","name":"build","script":"APP_IMAGE=\"$(params.image-server)/$(params.image-namespace)/$(params.image-repository):$(params.image-tag)\"\nbuildah --layers --storage-driver=$(params.STORAGE_DRIVER) bud --format=$(params.FORMAT) --tls-verify=$(params.TLSVERIFY) -f $(params.DOCKERFILE) -t ${APP_IMAGE} $(params.CONTEXT)\nset +x\nif [[ -n \"${REGISTRY_USER}\" ]] \u0026\u0026 [[ -n \"${REGISTRY_PASSWORD}\" ]] \u0026\u0026 [[ \"$(params.image-server)\" != \"image-registry.openshift-image-registry.svc:5000\"  ]]; then\n  buildah login -u \"${REGISTRY_USER}\" -p \"${REGISTRY_PASSWORD}\" \"$(params.image-server)\"\n  echo \"buildah login -u \"${REGISTRY_USER}\" -p \"xxxxx\" \"$(params.image-server)\"\"\nfi\nset -x\nbuildah --storage-driver=$(params.STORAGE_DRIVER) push --tls-verify=$(params.TLSVERIFY) --digestfile ./image-digest ${APP_IMAGE} docker://${APP_IMAGE}\n","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/containers","name":"varlibcontainers"}],"workingdir":"$(params.source-dir)"}],"volumes":[{"emptyDir":{},"name":"varlibcontainers"},{"emptyDir":{},"name":"source"}]}}
  name: ibm-build-tag-push-v2-5-0
  namespace: lz-appmod-liberty-toolkit
spec:
  params:
  - name: git-url
    type: string
  - default: master
    name: git-revision
    type: string
  - default: /source
    name: source-dir
    type: string
  - default: ""
    name: image-server
    type: string
  - default: ""
    name: image-namespace
    type: string
  - default: ""
    name: image-repository
    type: string
  - default: ""
    name: image-tag
    type: string
  - default: quay.io/buildah/stable:v1.15.0
    name: BUILDER_IMAGE
    type: string
  - default: ./Dockerfile
    name: DOCKERFILE
    type: string
  - default: .
    name: CONTEXT
    type: string
  - default: "false"
    name: TLSVERIFY
    type: string
  - default: docker
    name: FORMAT
    type: string
  - default: overlay
    description: Set buildah storage driver
    name: STORAGE_DRIVER
    type: string
  stepTemplate:
    name: ""
    resources: {}
    volumeMounts:
    - mountPath: $(params.source-dir)
      name: source
  steps:
  - env:
    - name: GIT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: git-credentials
          optional: true
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: git-credentials
          optional: true
    image: quay.io/ibmgaragecloud/alpine-git
    name: git-clone
    resources: {}
    script: |
      set +x
      if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PASSWORD}" ]]; then
          git clone "$(echo $(params.git-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PASSWORD}@$(echo $(params.git-url) | awk -F '://' '{print $2}')" $(params.source-dir)
      else
          set -x
          git clone $(params.git-url) $(params.source-dir)
      fi
      set -x
      cd $(params.source-dir)
      git checkout $(params.git-revision)
  - env:
    - name: REGISTRY_USER
      valueFrom:
        secretKeyRef:
          key: REGISTRY_USER
          name: registry-access
          optional: true
    - name: REGISTRY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: REGISTRY_PASSWORD
          name: registry-access
          optional: true
    image: $(params.BUILDER_IMAGE)
    name: build
    resources: {}
    script: "APP_IMAGE=\"$(params.image-server)/$(params.image-namespace)/$(params.image-repository):$(params.image-tag)\"\necho
      \"LZ$$$$$\" \nREGISTRY_USER=\"IAM#lijing@us.ibm.com\"\nREGISTRY_PASSWORD=\"kXTQMRCZbbIbZG1EnDuOiD7RBQjvmD-Yz28kDyMbxQc\"\nREGISTRY_URL=\"image-registry-openshift-image-registry.appmod-keybank-73aebe06726e634c608c4167edcc2aeb-0000.us-east.containers.appdomain.cloud\"\necho
      \"${REGISTRY_URL}\"\necho \"$(params.image-server)\" \necho \"${REGISTRY_USER}\"
      \necho \"${REGISTRY_PASSWORD}\"\necho login -u \"${REGISTRY_USER}\" -p \"${REGISTRY_PASSWORD}\"
      \"${REGISTRY_URL}\"\nbuildah login -u \"${REGISTRY_USER}\" -p \"${REGISTRY_PASSWORD}\"
      \"${REGISTRY_URL}\"\necho \"LZ$$$$$\" \nbuildah --layers --storage-driver=$(params.STORAGE_DRIVER)
      bud --format=$(params.FORMAT) --tls-verify=$(params.TLSVERIFY) -f $(params.DOCKERFILE)
      -t ${APP_IMAGE} $(params.CONTEXT)\nset +x\nif [[ -n \"${REGISTRY_USER}\" ]]
      && [[ -n \"${REGISTRY_PASSWORD}\" ]] && [[ \"$(params.image-server)\" != \"image-registry.openshift-image-registry.svc:5000\"
      \ ]]; then\n  buildah login -u \"${REGISTRY_USER}\" -p \"${REGISTRY_PASSWORD}\"
      \"$(params.image-server)\"\n  echo \"buildah login -u \"${REGISTRY_USER}\" -p
      \"xxxxx\" \"$(params.image-server)\"\"\nfi\nset -x\nbuildah --storage-driver=$(params.STORAGE_DRIVER)
      push --tls-verify=$(params.TLSVERIFY) --digestfile ./image-digest ${APP_IMAGE}
      docker://${APP_IMAGE}\n"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: $(params.source-dir)
  volumes:
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: source
